# Generated by Django 5.0.7 on 2024-07-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=9),
        ),
    ]
