# Generated by Django 5.0.7 on 2024-12-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_alter_vehicle_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleevent',
            name='mileage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=9),
        ),
    ]
